### ISSUE TITLE
mysqlclient 9.0 not able to load mysql_native_password.so

### ISSUE THREAD

**Issue by zhangyangyu** [shogo82148/actions-setup-mysql#1089]
Using mysqlclient 9.0 against old server using mysql_native_password fails.
![image](https://github.com/shogo82148/actions-setup-mysql/assets/3690895/a67a6902-afa9-48f7-ae2e-c84dc65e1f01)
According to the release note, mysql client will be backward compatible and the auth plugin change to a dynamic library.

**Comment by shogo82148** [comment]
Can you try v1.36.2?

**Comment by zhangyangyu** [comment]
@shogo82148 thanks for the fix. I've tested and it now succeeds on Ubuntu. But still fails with the same error on macOS. https://github.com/tidbcloud/ecosystem-integrations/actions/runs/9903666135/job/27359916603

**Comment by shogo82148** [comment]
@zhangyangyu try https://github.com/shogo82148/actions-setup-mysql/releases/tag/v1.36.3 please

**Comment by zhangyangyu** [comment]
@shogo82148 succeed on macos and ubuntu now. The last Windows has failure yet. https://github.com/tidbcloud/ecosystem-integrations/actions/runs/9922030023/job/27410766278

**Comment by shogo82148** [comment]
hmm, I looks that https://github.com/shogo82148/actions-setup-mysql/releases/download/v1.36.3/mysql-9.0.0-win32-x64.zip has "lib\plugin\mysql_native_password.ddl".
I don't know why it doesn't work :(

**Comment by zhangyangyu** [comment]
I know nothing about Windows, but I confirm the dynamic lib exists in the path. The only thing I suspect is powershell not able to correctly load the dll. So I tried `LIBMYSQL_PLUGIN_DIR` and seems it could work. See https://github.com/tidbcloud/ecosystem-integrations/actions/runs/9978219401/job/27574615014.
![image](https://github.com/user-attachments/assets/68fac935-308a-44a4-aa07-b4bce33a8b01)
I hard code the dir for test. Setting it to `$ToolPath/lib/plugin` might be a choice.

**Comment by shogo82148** [comment]
Good news.
Let’s change actions-setup-mysql to set the `LIBMYSQL_PLUGIN_DIR` environment variable.

**Comment by shogo82148** [comment]
https://github.com/shogo82148/actions-setup-mysql/pull/1098

**Comment by shogo82148** [comment]
released https://github.com/shogo82148/actions-setup-mysql/releases/tag/v1.36.4

**Comment by zhangyangyu** [comment]
nice! everything works successfully now.

**Comment by shogo82148** [comment]
👍🏼
