### ISSUE TITLE
Issue with certificates and MariaDB in Versions 11.4, 11.5, and 11.6

### ISSUE THREAD

**Issue by parpalak** [shogo82148/actions-setup-mysql#1136]
Hi, thanks for the MySQL action!

It seems that there's an issue with MariaDB versions 11.4, 11.5, and 11.6. The following error occurs:
```
Run mysql -e 'SELECT version();' -uroot
ERROR 2026 (HY000): TLS/SSL error: invalid CA certificate
Error: Process completed with exit code 1.
```

For reference, here’s an example close to documentation: https://github.com/parpalak/test_mysql_action/actions/runs/10719400842

**Comment by cuppett** [comment]
I'm hitting the same issue.

**Comment by pl38** [comment]
Me too
