### ISSUE TITLE
Document the multi-value syntax for my-cnf

### ISSUE THREAD

**Issue by indigoxela** [shogo82148/actions-setup-mysql#347]
Hi,
many thanks for this useful action!

Unfortunately I'm not able to guess the correct syntax for `my-cnf:` values.

The source code doesn't help me either, that's simply not my programming language. :wink:

What I got working:
```
my-cnf: 'datadir=/dev/shm/mysql'
```

How to get in `tmpdir=/dev/shm/mysql_tmp`? I tried all sorts of white space, escaped newlines, ...
No clue.

**Comment by shogo82148** [comment]
`my-cnf` have same syntax with `my.cnf` files.

```yaml
my-cnf: |
  datadir=/dev/shm/mysql
  tmpdir=/dev/shm/mysql_tmp
```

**Comment by indigoxela** [comment]
```
my-cnf: |
```
Now I feel really silly...

An example in the README might save the next person struggling with it some time.
